name: HoloItems
author: Aco
version: 1.0-STABLE-1.12
main: acodev.main
description: Holograms Showing the enchantments of an item!
depend: [HolographicDisplays]
commands:
    holoreload:
       description: Reload Configuration File